db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - ${SERVERNAME}-mysql:/var/lib/mysql
typo3:
  environment:
    CRONJOBS: ${CRONJOBS}
  expose:
  - "80"
  image: theinrichs/typo376:0.2
  links:
  - db:mysql
  volumes:
  - ${SERVERNAME}-typo3:/var/www/htdocs
  labels:
    de.netzpepper.proxyport: ${PROXYPORT}
    de.netzpepper.servername: www.${SERVERNAME}
access:
  image: theinrichs/sftp:0.7
  environment:
    PUBLICHOST: sftp.${SERVERNAME}
  expose:
  - "22"
  volumes:
  - ${SERVERNAME}-typo3:/data
  labels:
    de.netzpepper.sftp.servername: sftp.${SERVERNAME}