db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - ${SERVERNAME}-mysql:/var/lib/mysql
  - ${SERVERNAME}-config:/config/mysql
  labels:
    io.rancher.sidekicks: phpmyadmin
phpmyadmin:
  image: phpmyadmin/phpmyadmin
typo3:
  image: theinrichs/typo3_7-6:0.10
  expose:
  - "80"
  links:
  - db:mysql
  volumes:
  - ${SERVERNAME}-typo3:/var/www/htdocs
  - ${SERVERNAME}-config:/config/
  labels:
    io.rancher.sidekicks: access
    de.netzpepper.proxyport: ${PROXYPORT}
    de.netzpepper.servername: www.${SERVERNAME}
    de.netzpepper.redirects: ${SERVERNAME}
access:
  image: theinrichs/sftp:0.9
  expose:
  - "22"
  volumes:
  - ${SERVERNAME}-typo3:/data/typo3
  - ${SERVERNAME}-config:/data/config
  labels:
    de.netzpepper.sftp.servername: sftp.${SERVERNAME}

