db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - ${VHOSTNAME}_mysql/mysql:/var/lib/mysql
typo3:
  environment:
    VIRTUAL_HOST: ${VHOSTNAME}
  ports:
  - 80
  image: np/typo3:0.10
  links:
  - db:mysql
  volumes:
  - ${VHOSTNAME}_mysql/htdocs:/var/www/htdocs