db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - /var/docker/${VHOSTNAME}/mysql:/var/lib/mysql
typo3:
  environment:
    VIRTUAL_HOST: ${VHOSTNAME}
  ports:
  - 80
  image: np/typo3:0.9
  links:
  - db:mysql
  volumes:
  - /var/docker/${VHOSTNAME}/htdocs:/var/www/htdocs