db:
  environment:
    MYSQL_ROOT_PASSWORD: example
  image: mariadb
  volumes:
  - ${VHOSTNAME}-mysql:/var/lib/mysql
typo3:
  hostname: www.${VHOSTNAME}
  ports:
  - 80
  image: theinrichs/typo376:0.1
  links:
  - db:mysql
  volumes:
  - ${VHOSTNAME}-typo3:/var/www/htdocs